import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Check, Feather, FileText, LockKeyhole, Mic2, PenLine, Quote, ShieldCheck, Sparkles } from "lucide-react";
import { SiteLayout } from "@/components/site-layout";
import { Reveal } from "@/components/reveal";
import { CtaBanner, FaqAccordion, HeroReviewRatings, PlatformStrip, SectionHeading } from "@/components/sections";
import { GhostwritingForm } from "@/components/forms/ghostwriting-form";
import { GENRES } from "@/lib/site-data";
import editingDesk from "@/assets/editing-desk.jpg";
import videoInterview from "@/assets/video-interview.jpg";
import manuscript from "@/assets/blog-manuscript.jpg";
import openBook from "@/assets/open-book.jpg";

const TITLE = "Ghostwriting — Penova Publishers";
const DESC = "Ghostwriting for authors with a story to tell. Penova's writers learn your voice, shape your ideas and deliver a publication-ready book that still sounds unmistakably like you.";

export const Route = createFileRoute("/ghostwriting")({
  head: () => ({ meta: [{ title: TITLE }, { name: "description", content: DESC }, { property: "og:title", content: TITLE }, { property: "og:description", content: DESC }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: Page,
});

const processSteps = [
  { number: "01", icon: Mic2, title: "The conversation", body: "We listen before we outline. Through recorded interviews and thoughtful prompts, we find the stories, convictions and details only you can bring." },
  { number: "02", icon: FileText, title: "The architecture", body: "Your writer turns the raw material into a clear book map: chapter rhythm, narrative arc, key arguments and the moments readers will remember." },
  { number: "03", icon: PenLine, title: "The first draft", body: "Chapter by chapter, your manuscript takes shape. We write in your cadence, share progress at agreed milestones, and keep the work moving." },
  { number: "04", icon: Feather, title: "The refinement", body: "You respond, we listen, and the pages become more precise. Editorial passes bring pace, clarity and emotional truth without sanding away your voice." },
  { number: "05", icon: BookOpen, title: "The finished book", body: "You receive a polished, publication-ready manuscript with the files, rights and next steps needed to take your story into the world." },
];

const deliverables = ["A dedicated writer matched to your voice and subject", "Recorded interviews, transcripts and organised source material", "A chapter-by-chapter outline approved before drafting", "Regular draft reviews with a dedicated project lead", "Developmental editing, line editing and final proofread", "A publication-ready manuscript with full rights transferred"];

const ghostwritingFaqs = [
  { q: "What exactly does a ghostwriter do?", a: "A ghostwriter works behind the scenes to turn your experience, ideas or plot into a finished book. We interview you, research where needed, build the structure, write the chapters and refine the manuscript with you. Your name stays on the cover." },
  { q: "Will the finished book actually sound like me?", a: "That is the point of the process. We study your natural language, ask how you would explain an idea to a real person, and use interviews and draft feedback to learn your rhythm. The final manuscript should feel like your best, clearest self on the page." },
  { q: "How involved do I need to be?", a: "You decide the rhythm. Most projects include a series of focused interviews, outline approval, and chapter reviews at agreed milestones. We do the heavy writing; you remain the creative authority throughout." },
  { q: "Who owns the manuscript and the rights?", a: "You do. Penova is a services partner, not a rights-acquiring publisher. Once the engagement is complete, the manuscript, source files and usage rights belong to you permanently." },
  { q: "Can you finish a book I have already started?", a: "Yes. Half-finished books are often a strong starting point. We assess what is working, preserve the material that feels most like you, and create a practical route to complete the manuscript." },
  { q: "How long does a ghostwritten book take?", a: "Most full-length projects take four to nine months, depending on length, research and interview cadence. We give you a written schedule before drafting starts and flag any changes early." },
];

function WritingTicker() {
  const phrases = ["your voice", "your history", "your idea"];
  const [phraseIndex, setPhraseIndex] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setPhraseIndex((current) => (current + 1) % phrases.length), 2800); return () => window.clearInterval(timer); }, [phrases.length]);
  return <span className="ghostwriting-ticker" aria-live="polite">{phrases[phraseIndex]}<span className="ghostwriting-caret" aria-hidden="true" /></span>;
}

function ProcessCard({ step, index }: { step: (typeof processSteps)[0]; index: number }) {
  const Icon = step.icon;
  return <Reveal as="li" delay={index * 80} className="group relative"><div className="ghostwriting-process-number">{step.number}</div><div className="mt-8 flex h-12 w-12 items-center justify-center rounded-full border border-gold/30 bg-gold/10 text-gold transition-all duration-500 group-hover:border-gold group-hover:bg-gold group-hover:text-navy-deep group-hover:shadow-[0_0_26px_rgba(212,175,55,0.3)]"><Icon className="h-5 w-5 transition-transform duration-500 group-hover:rotate-[-8deg]" /></div><h3 className="mt-6 font-serif text-2xl text-white">{step.title}</h3><p className="mt-3 text-sm leading-relaxed text-white/65">{step.body}</p></Reveal>;
}

function Page() {
  return <SiteLayout>
    <style>{`@keyframes ghostwriting-caret{0%,45%{opacity:1}46%,100%{opacity:0}}@keyframes ghostwriting-write{0%{transform:translateX(-18px) rotate(-18deg);opacity:0}18%,82%{opacity:1}100%{transform:translateX(42px) rotate(-8deg);opacity:0}}@keyframes ghostwriting-page{0%,100%{transform:rotateX(2deg) rotateY(-2deg) translateY(0)}50%{transform:rotateX(0deg) rotateY(2deg) translateY(-8px)}}@keyframes ghostwriting-ink{0%,100%{stroke-dashoffset:120;opacity:.15}45%,70%{stroke-dashoffset:0;opacity:.8}}@keyframes ghostwriting-float{0%,100%{transform:translateY(0) rotate(2deg)}50%{transform:translateY(-10px) rotate(-1deg)}}.ghostwriting-ticker{display:inline-flex;align-items:center;min-width:8.5ch;color:#d4af37}.ghostwriting-caret{width:2px;height:.85em;margin-left:5px;background:#d4af37;animation:ghostwriting-caret 1s steps(1) infinite}.ghostwriting-pen{animation:ghostwriting-write 4s ease-in-out infinite;transform-origin:80% 80%}.ghostwriting-page{animation:ghostwriting-page 7s ease-in-out infinite;transform-origin:center}.ghostwriting-ink{stroke-dasharray:120;animation:ghostwriting-ink 4s ease-in-out infinite}.ghostwriting-float{animation:ghostwriting-float 6s ease-in-out infinite}.ghostwriting-process-number{font-family:'Cormorant Garamond',Georgia,serif;font-size:4rem;line-height:1;color:rgba(212,175,55,.22);transition:color .4s ease}.group:hover .ghostwriting-process-number{color:rgba(212,175,55,.75)}@media (prefers-reduced-motion:reduce){.ghostwriting-pen,.ghostwriting-page,.ghostwriting-ink,.ghostwriting-float,.ghostwriting-caret{animation:none}}`}</style>

    <section className="relative isolate overflow-hidden bg-navy-deep"><img src={editingDesk} alt="A writer drafting a manuscript by lamplight" className="absolute inset-0 -z-20 h-full w-full object-cover object-center opacity-55" fetchPriority="high" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-navy-deep via-navy-deep/80 to-navy-deep/35" /><div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_78%_35%,rgba(212,175,55,0.2),transparent_38%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-24 lg:grid-cols-[1.05fr_0.95fr] lg:px-8 lg:py-32">
      <Reveal><span className="glass-navy inline-flex items-center gap-2 rounded-full px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.2em] text-gold"><PenLine className="h-3.5 w-3.5" />Ghostwriting studio</span><h1 className="mt-8 max-w-3xl text-5xl leading-[1.02] text-on-navy md:text-6xl lg:text-7xl">The book is in you.<span className="mt-3 block text-gold-shimmer">We bring it to the page.</span></h1><span className="rule-gold mt-8" /><p className="mt-8 max-w-2xl text-lg leading-relaxed text-on-navy-muted md:text-xl">A thoughtful ghostwriter gives shape to <WritingTicker /> — without taking the story away from you.</p><div className="mt-10 flex flex-wrap gap-3"><Link to="/contact" className="beam-sweep group inline-flex items-center gap-2 rounded-sm bg-gold px-8 py-4 text-sm font-semibold text-navy-deep transition-all duration-500 hover:-translate-y-0.5 hover:bg-gold-light hover:shadow-glow">Start the conversation<ArrowRight className="h-4 w-4 transition-transform duration-500 group-hover:translate-x-1" /></Link><a href="#process" className="inline-flex items-center gap-2 rounded-sm border border-on-navy/30 px-8 py-4 text-sm font-semibold text-on-navy transition-all duration-500 hover:-translate-y-0.5 hover:border-gold hover:text-gold">See how it works</a></div><HeroReviewRatings className="mt-9" /><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 text-xs font-semibold uppercase tracking-[0.16em] text-on-navy-muted"><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-gold" />You keep the rights</span><span className="inline-flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-gold" />Confidential by design</span></div></Reveal>
      <Reveal delay={180} className="relative mx-auto w-full max-w-[480px]"><GhostwritingForm /></Reveal>
    </div></section>

    <PlatformStrip />
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-14 lg:grid-cols-[0.92fr_1.08fr] lg:items-center"><Reveal className="relative"><div className="overflow-hidden rounded-2xl border border-border/60 bg-cream shadow-[0_24px_60px_rgba(15,27,45,0.14)]"><img src={videoInterview} alt="An author sharing their story in a library" className="aspect-[4/3] w-full object-cover transition-transform duration-[1800ms] hover:scale-105" /></div><div className="absolute -bottom-7 -right-5 hidden rounded-xl border border-white/70 bg-white/95 p-5 shadow-xl backdrop-blur-md sm:block"><Quote className="h-6 w-6 text-gold" /><p className="mt-2 max-w-[170px] font-serif text-xl leading-tight text-navy-deep">Write it like you mean it.</p></div></Reveal><Reveal delay={120}><SectionHeading eyebrow="The invisible craft" title="A book that sounds like you on your clearest day." intro="The best ghostwriting is almost invisible. It carries your experience, your point of view and your particular way of seeing the world, then gives it the structure and momentum readers need." /><div className="mt-10 grid gap-5 sm:grid-cols-2">{[["Voice before volume", "We learn your language before we chase a word count."], ["Human, always", "Real conversations and considered craft. No automated manuscript shortcuts."], ["A partner, not a proxy", "You remain close to the decisions that make the book yours."], ["Built for publication", "The final pages are polished to move confidently into production."]].map(([title, body]) => <div key={title} className="border-l-2 border-gold/50 pl-4"><h3 className="font-serif text-xl text-navy-deep">{title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{body}</p></div>)}</div></Reveal></div></section>

    <section className="border-y border-border/60 bg-cream-deep py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><SectionHeading eyebrow="Every kind of story" title="The subject may change. The standard does not." intro="Memoir, thought leadership, fiction or the book you cannot quite categorise yet. We match the writer to the work, then build a process around the truth of it." /></Reveal><div className="mt-14 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{GENRES.map((genre, index) => <Reveal key={genre} delay={index * 45}><div className="group flex min-h-16 items-center gap-3 rounded-md border border-border bg-white px-4 py-3 transition-all duration-300 hover:-translate-y-1 hover:border-gold/50 hover:shadow-[0_12px_25px_rgba(212,175,55,0.12)]"><span className="h-2 w-2 shrink-0 rounded-full bg-gold/50 transition-colors group-hover:bg-gold" /><span className="text-sm font-semibold text-navy-deep">{genre}</span></div></Reveal>)}</div></div></section>

    <section id="process" className="relative overflow-hidden bg-navy-deep py-24 lg:py-32"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(212,175,55,0.16),transparent_42%)]" /><div className="relative mx-auto max-w-7xl px-5 lg:px-8"><Reveal><SectionHeading eyebrow="The writing room" title="From lived experience to finished manuscript." intro="A clear, human process keeps the work intimate without letting it drift. You always know what happens next." onNavy /></Reveal><ol className="mt-16 grid gap-12 md:grid-cols-2 lg:grid-cols-5 lg:gap-7">{processSteps.map((step, index) => <ProcessCard key={step.number} step={step} index={index} />)}</ol></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:items-center"><Reveal><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brown">What arrives at the end</p><h2 className="mt-4 max-w-xl font-serif text-4xl tracking-tight text-navy-deep md:text-5xl">A manuscript you can stand behind.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground">The relationship may be quiet, but the finished work should have presence. We hand over a manuscript that is structurally sound, beautifully written and ready for its next stage.</p><ul className="mt-8 grid gap-4 sm:grid-cols-2">{deliverables.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed text-navy-deep"><Check className="mt-0.5 h-4 w-4 shrink-0 text-gold" />{item}</li>)}</ul><Link to="/contact" className="mt-10 inline-flex items-center gap-2 text-sm font-semibold uppercase tracking-widest text-navy-deep underline decoration-gold decoration-2 underline-offset-8 transition-colors hover:text-gold">Talk through your book <ArrowRight className="h-4 w-4" /></Link></Reveal><Reveal delay={120} className="relative"><div className="overflow-hidden rounded-2xl border border-border/60 bg-navy-deep shadow-[0_24px_60px_rgba(15,27,45,0.16)]"><img src={openBook} alt="An open book ready for its next chapter" className="aspect-[4/3] w-full object-cover opacity-80 transition-transform duration-[1800ms] hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-navy-deep/70 via-transparent to-transparent" /><div className="absolute bottom-7 left-7 right-7 flex items-end justify-between gap-4 text-white"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">The handover</p><p className="mt-2 font-serif text-3xl">Your name. Your book.</p></div><BookOpen className="h-8 w-8 text-gold" /></div></div></Reveal></div></section>

    <section className="bg-cream-deep py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><Reveal><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brown">A word from the desk</p><blockquote className="mt-5 font-serif text-3xl leading-tight text-navy-deep md:text-4xl">“When I read the first draft, it sounded like me on my best day.”</blockquote><div className="mt-7 h-px w-14 bg-gold" /><p className="mt-4 text-sm font-semibold uppercase tracking-[0.16em] text-navy-deep">Dr. Aaron Whitfield</p><p className="mt-1 text-sm italic text-brown">The Quiet Operating Room</p></Reveal><Reveal delay={100}><div className="grid gap-5 sm:grid-cols-2"><div className="rounded-md border border-border bg-white p-7"><Mic2 className="h-6 w-6 text-gold" /><h3 className="mt-5 font-serif text-2xl text-navy-deep">Your story, heard</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Every project starts with a real conversation, not a form letter. We make space for the details that give a book its pulse.</p></div><div className="rounded-md border border-border bg-white p-7"><ShieldCheck className="h-6 w-6 text-gold" /><h3 className="mt-5 font-serif text-2xl text-navy-deep">Your work, protected</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Confidentiality, plain-English scopes and full rights transfer are part of the service from the first call.</p></div></div></Reveal></div></section>

    <section className="mx-auto max-w-5xl px-5 py-24 lg:px-8 lg:py-32"><Reveal><SectionHeading eyebrow="Questions authors ask" title="The quiet part, made clear." intro="Ghostwriting works best when expectations are open from the beginning." /></Reveal><div className="mt-12"><FaqAccordion items={ghostwritingFaqs} /></div></section>
    <CtaBanner title="The story is yours. Let’s write it properly." body="Tell us what you have, what you want the book to become, and where you feel stuck. We will come back with an honest route, a clear scope and a fixed quote." primary="Talk to a senior editor" />
  </SiteLayout>;
}
