/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChildrensBooksRouteImport } from './routes/childrens-books'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EditingRouteImport } from './routes/editing'
import { Route as GhostwritingRouteImport } from './routes/ghostwriting'
import { Route as IllustrationRouteImport } from './routes/illustration'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyChoicesRouteImport } from './routes/privacy-choices'
import { Route as PublishingRouteImport } from './routes/publishing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrensBooksRoute = ChildrensBooksRouteImport.update({
  id: '/childrens-books',
  path: '/childrens-books',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingRoute = EditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostwritingRoute = GhostwritingRouteImport.update({
  id: '/ghostwriting',
  path: '/ghostwriting',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationRoute = IllustrationRouteImport.update({
  id: '/illustration',
  path: '/illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyChoicesRoute = PrivacyChoicesRouteImport.update({
  id: '/privacy-choices',
  path: '/privacy-choices',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishingRoute = PublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/childrens-books': typeof ChildrensBooksRoute
  '/contact': typeof ContactRoute
  '/editing': typeof EditingRoute
  '/ghostwriting': typeof GhostwritingRoute
  '/illustration': typeof IllustrationRoute
  '/marketing': typeof MarketingRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-choices': typeof PrivacyChoicesRoute
  '/publishing': typeof PublishingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/childrens-books': typeof ChildrensBooksRoute
  '/contact': typeof ContactRoute
  '/editing': typeof EditingRoute
  '/ghostwriting': typeof GhostwritingRoute
  '/illustration': typeof IllustrationRoute
  '/marketing': typeof MarketingRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-choices': typeof PrivacyChoicesRoute
  '/publishing': typeof PublishingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/childrens-books': typeof ChildrensBooksRoute
  '/contact': typeof ContactRoute
  '/editing': typeof EditingRoute
  '/ghostwriting': typeof GhostwritingRoute
  '/illustration': typeof IllustrationRoute
  '/marketing': typeof MarketingRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-choices': typeof PrivacyChoicesRoute
  '/publishing': typeof PublishingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/childrens-books'
    | '/contact'
    | '/editing'
    | '/ghostwriting'
    | '/illustration'
    | '/marketing'
    | '/offer'
    | '/privacy'
    | '/privacy-choices'
    | '/publishing'
    | '/signup'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/childrens-books'
    | '/contact'
    | '/editing'
    | '/ghostwriting'
    | '/illustration'
    | '/marketing'
    | '/offer'
    | '/privacy'
    | '/privacy-choices'
    | '/publishing'
    | '/signup'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/childrens-books'
    | '/contact'
    | '/editing'
    | '/ghostwriting'
    | '/illustration'
    | '/marketing'
    | '/offer'
    | '/privacy'
    | '/privacy-choices'
    | '/publishing'
    | '/signup'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChildrensBooksRoute: typeof ChildrensBooksRoute
  ContactRoute: typeof ContactRoute
  EditingRoute: typeof EditingRoute
  GhostwritingRoute: typeof GhostwritingRoute
  IllustrationRoute: typeof IllustrationRoute
  MarketingRoute: typeof MarketingRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyChoicesRoute: typeof PrivacyChoicesRoute
  PublishingRoute: typeof PublishingRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/childrens-books': {
      id: '/childrens-books'
      path: '/childrens-books'
      fullPath: '/childrens-books'
      preLoaderRoute: typeof ChildrensBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing': {
      id: '/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof EditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghostwriting': {
      id: '/ghostwriting'
      path: '/ghostwriting'
      fullPath: '/ghostwriting'
      preLoaderRoute: typeof GhostwritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustration': {
      id: '/illustration'
      path: '/illustration'
      fullPath: '/illustration'
      preLoaderRoute: typeof IllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-choices': {
      id: '/privacy-choices'
      path: '/privacy-choices'
      fullPath: '/privacy-choices'
      preLoaderRoute: typeof PrivacyChoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing': {
      id: '/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof PublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChildrensBooksRoute: ChildrensBooksRoute,
  ContactRoute: ContactRoute,
  EditingRoute: EditingRoute,
  GhostwritingRoute: GhostwritingRoute,
  IllustrationRoute: IllustrationRoute,
  MarketingRoute: MarketingRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyChoicesRoute: PrivacyChoicesRoute,
  PublishingRoute: PublishingRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
